### ISSUE TITLE
v0.9 ToDo

### ISSUE THREAD

**Issue by nurse** [treasure-data/perfectqueue#50]
PerfectQueue v0.9 TODOs

- [x] UPDATE first strategy #15
- [x] Remove cancel_request (it's not compatible with v0.7) #51 
- [ ] heartbeat; check before run the task
- [ ] Don't touch created_at and resource

Postpone to v1.0
- Don’t fill nil into created_at and resource
- extend config of initialize; delete RDBBackend’s argument and pass to Sqlite
